#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -x

cd $OPENSHIFT_REPO_DIR

#nohup java -jar target/*.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &
#nohup java -Xms384m -Xmx412m -jar build/libs/*.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} --spring.profiles.active=openshift --logging.file=${OPENSHIFT_LOG_DIR}app.log &
bash gradlew runAll

#sleep 30 # wait a little for spring bootstrapping...
